- name: install nginx
  become: yes
  apt: >
    name=nginx
    update_cache=true
    state=latest

#- name: Copy nginx.conf
#  become: yes
#  template: src=nginx.conf.j2
#            dest=/etc/nginx/nginx.conf
#  notify: reload nginx
